GET http://localhost:3000/

###
POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "outrano",
  "password": "123456"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "outrano",
  "password": "123456"
}

###

GET http://localhost:3000/profile

###

GET http://localhost:3000/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im91dHJhbm8iLCJzdWIiOjQsImlhdCI6MTY1OTU4NzY2OX0.NAKn_TvrvA9E_t5na-exOHNnebBcRVZlpZEEWsKP7FY
